In [1]:
import torch
import numpy as np


In [2]:
t= torch.FloatTensor([0. ,1. ,2., 3., 4.])

In [3]:
print(t.dim())
print(t.shape)
print(t.size())

1
torch.Size([5])
torch.Size([5])


In [4]:
print(t[0],t[1],)

tensor(0.) tensor(1.)


In [5]:
t2 = torch.FloatTensor([[1.,2.,3.,],
                        
                        [4.,5.,6.,],
                        [7.,8.,9.,],
                        [10.,11.,12.,],])

In [6]:
print(t2.dim())
print(t2.shape)
print(t2.size())

2
torch.Size([4, 3])
torch.Size([4, 3])


In [7]:
## 콤마 ,1 은 두번째꺼
t2[:,1]

tensor([ 2.,  5.,  8., 11.])

In [8]:
## 맨 마지막 제외 
t2[:,:-1]

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])

In [9]:
## m2의 0 인덱스를 m1에 더하고 1 인덱스는 m2에
m1 = torch.FloatTensor([[6,2],])
m2 = torch.FloatTensor([[2], [3]])

In [10]:
m1 + m2 

tensor([[8., 4.],
        [9., 5.]])

In [11]:
## m1의 각자 인덱스의 곱에 m2의 동일 인덱스를 곱해서 더한다
m1 = torch.FloatTensor([[3,2],[2,3]])
m2 = torch.FloatTensor([[2], [3]])

In [12]:
m1.matmul(m2)

tensor([[12.],
        [13.]])

In [13]:
## m2의 0 인덱스를 m1에 곱하고 1 인덱스는 m2에 곱
m1.mul(m2)

tensor([[6., 4.],
        [6., 9.]])

In [14]:
t = torch.FloatTensor([1.,2.])

In [15]:
t.mean()

tensor(1.5000)

In [16]:
## 정수형이라 평균 x
t2 = torch.LongTensor([1,2])
t2.mean()

In [19]:
## 차원을 볼때 chunk 단위로 생각 dim 2 = 두개의 큰 묶음에서 계산 / dim =1 가장 작은 단위 묶음에서 계산 / dim=0 은 각각의 행렬인덱스를 연산
t = torch.FloatTensor([
    [[1.,2.,3.,3.], 
    [4.,5.,6.,0.],
    [7.,8.,9.,0.]],

     [[1.,4.,3.,7.], 
    [4.,6.,6.,0.],
    [7.,9.,9.,0.]]
                       ])

In [20]:
## dim에 따라서 행렬이 정해진다.
## dim = 0 -> 3*4 행렬
## dim =1  -> 2*4 행렬
## dim = 2 -> 2*3 행렬
t.size()

torch.Size([2, 3, 4])

In [22]:

t.sum(dim=1)

tensor([[12., 15., 18.,  3.],
        [12., 19., 18.,  7.]])

In [23]:
## 가장큰 인덱스 
t.argmax(axis=0)

tensor([[0, 1, 0, 1],
        [0, 1, 0, 0],
        [0, 1, 0, 0]])

In [59]:
t.mean()

tensor(2.3333)

In [60]:
# 삼차원일때 axis 1 = 열 -1 은 마지막 열
t.mean(axis=-1)

tensor([[1.5000, 3.5000, 2.0000]])

In [69]:
t.mean(axis=0)

tensor([[1., 2.],
        [3., 4.],
        [2., 2.]])

In [24]:
## 2차원일때 axis=1 은 행
t.sum(axis=0)

tensor([[ 2.,  6.,  6., 10.],
        [ 8., 11., 12.,  0.],
        [14., 17., 18.,  0.]])

In [75]:
## indices 인덱스 1이 크다 // 행에서 큰값
t.max(axis=1)

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

In [25]:
## 열끼리 max indices 열에서의 인덱스 반환
t.max(axis=0)

torch.return_types.max(
values=tensor([[1., 4., 3., 7.],
        [4., 6., 6., 0.],
        [7., 9., 9., 0.]]),
indices=tensor([[0, 1, 0, 1],
        [0, 1, 0, 0],
        [0, 1, 0, 0]]))

In [26]:
## 행끼리 마지막 차원
t.max(axis=-1)

torch.return_types.max(
values=tensor([[3., 6., 9.],
        [7., 6., 9.]]),
indices=tensor([[2, 2, 2],
        [3, 1, 1]]))

In [30]:
t = torch.FloatTensor([
    [[1.,2.,3.], 
    [4.,5.,6.]
    ],
     [[1.,4.,3.], 
    [4.,6.,3.]]
                       ])

In [31]:
t.size()

torch.Size([2, 2, 3])

In [46]:
## 첫번째 차원은 토치에 맡기고 두번째 차원 길이는 6을 가지도록
t.view([-1,6
        ])

tensor([[1., 2., 3., 4., 5., 6.],
        [1., 4., 3., 4., 6., 3.]])

In [48]:

t.view([-1,6]).shape

torch.Size([2, 6])

In [49]:
t.view([-1,1,3]).size()

torch.Size([4, 1, 3])

In [53]:
t= torch.FloatTensor([[[0],[1],[2]]])
t.size()

torch.Size([1, 3, 1])

In [56]:
t

tensor([[[0.],
         [1.],
         [2.]]])

In [54]:
t2= t.squeeze()

In [58]:
t2.shape

torch.Size([3])

In [152]:
t2.unsqueeze(dim=-1)

tensor([[0.],
        [1.],
        [2.]])

In [155]:
x= torch.FloatTensor([[1,2],[3,4]])
y= torch.FloatTensor([[6,7],[3,4]])

In [163]:
torch.cat([x,y], dim=-1)

tensor([[1., 2., 6., 7.],
        [3., 4., 3., 4.]])

In [3]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [4]:
torch.stack([x,y,z])

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [5]:
torch.stack([x,y,z], dim =1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [9]:
torch.cat([x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0)], dim=0)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [11]:
x = torch.FloatTensor([[0,1,2],
                      [3,4,5]])

In [12]:
## x 와 동일한 형태의 0으로 채운 행렬
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
## x 와 동일한 형태의 1로 채운 행렬
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [14]:
x = torch.FloatTensor([[1,2],
                      [3,4]])

In [15]:
x.mul(2)

tensor([[2., 4.],
        [6., 8.]])

In [16]:
## _ == inplace =True
x.mul_(2)

tensor([[2., 4.],
        [6., 8.]])

In [17]:
x

tensor([[2., 4.],
        [6., 8.]])

------------------ 토치를 이용한 모델 생성 

In [59]:
import torch
import random
import torchvision.datasets as dsets
from torchvision import transforms

In [60]:
## pytorch gpu 설정
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [61]:
random.seed(777)
torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [62]:
## root = directory / train =true (train data) / transform= 형태
mnist_train =dsets.MNIST(root='MNIST_data/', train=True, transform= transforms.ToTensor(), download=True)
mnist_test =dsets.MNIST(root='MNIST_data/', train=False, transform= transforms.ToTensor(), download=True)

  0%|          | 0/9912422 [00:00<?, ?it/s]

Extracting MNIST_data/MNIST/raw/train-images-idx3-ubyte.gz to MNIST_data/MNIST/raw



  0%|          | 0/28881 [00:00<?, ?it/s]

Extracting MNIST_data/MNIST/raw/train-labels-idx1-ubyte.gz to MNIST_data/MNIST/raw



  0%|          | 0/1648877 [00:00<?, ?it/s]

Extracting MNIST_data/MNIST/raw/t10k-images-idx3-ubyte.gz to MNIST_data/MNIST/raw



  0%|          | 0/4542 [00:00<?, ?it/s]

Extracting MNIST_data/MNIST/raw/t10k-labels-idx1-ubyte.gz to MNIST_data/MNIST/raw



In [64]:
## drop_last = batch size 안맞는거 날림
data_loader = torch.utils.data.DataLoader(mnist_train, batch_size =128, shuffle=True, drop_last=True)

In [65]:
## pytorch 는 gpu 사용 여부를 모델에 넣어줌
## init layer
linear = torch.nn.Linear(784, 10, bias=True).to(device)
## weight initializing -> weight regularization
torch.nn.init.normal_(linear.weight)

Parameter containing:
tensor([[-1.2901,  0.3930, -0.1891,  ..., -0.1626, -0.3275,  0.5608],
        [-1.6757, -0.2454,  0.9221,  ...,  0.9559,  0.6160, -0.4226],
        [ 0.2444,  1.4810, -2.0906,  ...,  0.1206,  1.0044, -0.3737],
        ...,
        [ 0.6234,  1.8019, -2.7563,  ..., -0.5889, -0.5576,  0.7360],
        [-0.2871, -1.3313, -2.2248,  ...,  0.0309,  0.9180, -0.1482],
        [ 0.7678,  0.6624, -0.5362,  ...,  0.2338,  0.3688, -0.7182]],
       device='cuda:0', requires_grad=True)

In [74]:
## 손실함수 
criterion = torch.nn.CrossEntropyLoss().to(device)
## optimizer
optimizer = torch.optim.Adam(linear.parameters(), lr =0.001 )


In [75]:
total_batch = len(data_loader)

for epoch in range(15):
  avg_cost = 0
  for X,Y in data_loader:
    X = X.view(-1, 28*28).to(device)
    Y = Y.to(device)

    ## 0으로 초기화
    optimizer.zero_grad()
    hypothesis =linear(X)
    ##  손실 구하기 위해 예측값과 정답
    cost = criterion(hypothesis , Y)
    cost.backward()
    ## lr 로 weight  수정
    optimizer.step()

    avg_cost += cost / total_batch
  print('epoch', '%04d'%(epoch+1), 'cost = ','{:.9f}'.format(avg_cost))

epoch 0001 cost =  6.380524635
epoch 0002 cost =  1.998547912
epoch 0003 cost =  1.292787313
epoch 0004 cost =  1.003703475
epoch 0005 cost =  0.843536735
epoch 0006 cost =  0.738739789
epoch 0007 cost =  0.665791750
epoch 0008 cost =  0.610927165
epoch 0009 cost =  0.567630112
epoch 0010 cost =  0.533421874
epoch 0011 cost =  0.505116343
epoch 0012 cost =  0.481722206
epoch 0013 cost =  0.462168694
epoch 0014 cost =  0.444652528
epoch 0015 cost =  0.429568201


In [76]:
## 검증시 전체 데이터셋의 정확도
with torch.no_grad():
  x_test = mnist_test.data.view(-1,28*28).float().to(device)
  y_test = mnist_test.targets.to(device)

  prediction = linear(x_test)
  correct = torch.argmax(prediction, 1) == y_test
  accuracy = correct.float().mean()
  print('acc = ', accuracy.item())

acc =  0.886199951171875


In [78]:
x_test.shape

torch.Size([10000, 784])

In [46]:
## 데이터 1개 검증
with torch.no_grad():
  x_test = mnist_test.data[0].view(-1,28*28).float().to(device)
  y_test = mnist_test.targets[0].to(device)

  prediction = linear(x_test)
  correct = torch.argmax(prediction, 1).item()
  #accuracy = correct.float().mean()
  print('label = ', y_test.item())
  print('pred = ', correct)

label =  7
pred =  7


In [61]:
linear1 = torch.nn.Linear(784, 256, bias=True).to(device)
linear2= torch.nn.Linear(256, 256, bias=True).to(device)
linear3 = torch.nn.Linear(256, 10, bias=True).to(device)
relu =torch.nn.ReLU()
torch.nn.init.normal_(linear1.weight)
torch.nn.init.normal_(linear2.weight)
torch.nn.init.normal_(linear3.weight)

model = torch.nn.Sequential(linear1, relu, linear2, relu, linear3)

In [62]:
## 손실함수 
criterion = torch.nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr =0.001 )

In [64]:

for epoch in range(15):
  avg_cost = 0
  for X,Y in data_loader:
    ## 784 형태 아무거나 가능
    X = X.view(-1, 784).to(device)
    Y = Y.to(device)

    ## 0으로 초기화
    optimizer.zero_grad()
    hypothesis =model(X)
    ##  손실 구하기 위해 예측값과 정답
    cost = criterion(hypothesis , Y)
    cost.backward()
    ## lr 로 weight  수정
    optimizer.step()

    avg_cost += cost / total_batch
  print('epoch', '%04d'%(epoch+1), 'cost = ','{:.9f}'.format(avg_cost))

epoch 0001 cost =  0.706371605
epoch 0002 cost =  0.523155212
epoch 0003 cost =  0.493103296
epoch 0004 cost =  0.441637039
epoch 0005 cost =  0.398084998
epoch 0006 cost =  0.331055909
epoch 0007 cost =  0.307540685
epoch 0008 cost =  0.262950808
epoch 0009 cost =  0.267807215
epoch 0010 cost =  0.222561657
epoch 0011 cost =  0.295874715
epoch 0012 cost =  0.223108202
epoch 0013 cost =  0.227018997
epoch 0014 cost =  0.178316757
epoch 0015 cost =  0.201562077


In [68]:

linear1 = torch.nn.Linear(784, 256, bias=True).to(device)
linear2= torch.nn.Linear(256, 256, bias=True).to(device)
linear3 = torch.nn.Linear(256, 10, bias=True).to(device)
relu =torch.nn.ReLU()
dropout = torch.nn.Dropout(0.5)
bn = torch.nn.BatchNorm1d(256)

## weight init 
torch.nn.init.xavier_uniform_(linear1.weight)
torch.nn.init.xavier_uniform_(linear2.weight)
torch.nn.init.xavier_uniform_(linear3.weight)

model = torch.nn.Sequential(linear1, bn, relu,dropout, linear2, relu, dropout, linear3).to(device)

In [69]:
## 손실함수 
criterion = torch.nn.CrossEntropyLoss().to(device)
optimizer = torch.optim.Adam(model.parameters(), lr =0.001 )

In [70]:

for epoch in range(15):
  avg_cost = 0
  for X,Y in data_loader:
    ## 784 형태 아무거나 가능
    X = X.view(-1, 784).to(device)
    Y = Y.to(device)

    ## 0으로 초기화
    optimizer.zero_grad()
    hypothesis =model(X)
    ##  손실 구하기 위해 예측값과 정답
    cost = criterion(hypothesis , Y)
    cost.backward()
    ## lr 로 weight  수정
    optimizer.step()

    avg_cost += cost / total_batch
  print('epoch', '%04d'%(epoch+1), 'cost = ','{:.9f}'.format(avg_cost))

epoch 0001 cost =  0.475391388
epoch 0002 cost =  0.247949824
epoch 0003 cost =  0.201226979
epoch 0004 cost =  0.171910092
epoch 0005 cost =  0.153527454
epoch 0006 cost =  0.140286386
epoch 0007 cost =  0.128859505
epoch 0008 cost =  0.120887682
epoch 0009 cost =  0.111301221
epoch 0010 cost =  0.110113539
epoch 0011 cost =  0.101844870
epoch 0012 cost =  0.096199475


KeyboardInterrupt: ignored